spring.config.import=optional:file:.env[.properties]

spring.application.name=app

# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.ttl-seconds=${JWT_TTL_SECONDS}
app.jwt.issuer=apex-backend

# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
